#!/usr/bin/env bash

# ---------------------------------------------------------------------------------------- #
# Description                                                                              #
# ---------------------------------------------------------------------------------------- #
#                                                                                          #
# ---------------------------------------------------------------------------------------- #

PROMPT='Are you sure you want to commit to the master branch? [Yes/No] '

# ---------------------------------------------------------------------------------------- #
# Description                                                                              #
# ---------------------------------------------------------------------------------------- #
#                                                                                          #
# ---------------------------------------------------------------------------------------- #

function check_for_confirmation
{
    local valid_response=false
    local return_code=2

    # Allows us to read user input below, assigns stdin to keyboard
    exec < /dev/tty

    while [[ "${valid_response}" = false ]]
    do
        read -r -p "${PROMPT}" response
        case $response in
            [yY][eE][sS]|[yY])
                valid_response=true
                return_code=0
                ;;
            [nN][oO]|[nN])
                valid_response=true
                return_code=1
                ;;
            *)
                ;;
        esac
    done
    # Reclose STDIO
    exec <&-
    echo "${return_code}"
}

# ---------------------------------------------------------------------------------------- #
# Main()                                                                                   #
# ---------------------------------------------------------------------------------------- #
# The main function where all of the heavy lifting and script config is done.              #
# ---------------------------------------------------------------------------------------- #
function main()
{
    local confirmation=0

    if branch=$(git rev-parse --abbrev-ref HEAD 2>&1); then
        if [[ "${branch}" = "master" ]]; then
            confirmation=$(check_for_confirmation)
        fi
    fi
   exit "${confirmation}"
}

# ---------------------------------------------------------------------------------------- #
# Main()                                                                                   #
# ---------------------------------------------------------------------------------------- #
# The actual 'script' and the functions/sub routines are called in order.                  #
# ---------------------------------------------------------------------------------------- #

main "${@}"

# ---------------------------------------------------------------------------------------- #
# End of Script                                                                            #
# ---------------------------------------------------------------------------------------- #
# This is the end - nothing more to see here.                                              #
# ---------------------------------------------------------------------------------------- #
